### ISSUE TITLE
Kalipso crashes when opening certain IP-addresses to view timewindows

### ISSUE THREAD

**Issue by Locituscom** [stratosphereips/StratosphereLinuxIPS#104]
Now that I've gotten kalipso up and running and viewing my traffic, some IP addresses crash kalipso while others work as expected. The crash output looks like this:

Viewing timewindows for IP 192.168.3.3 crashes kalipso, but viewing IP 192.168.3.4 works fine.

mr@ids:/opt/StratosphereLinuxIPS$ ./kalipso.sh
TypeError: text.replace is not a function
    at Object.helpers.stripTags (/opt/StratosphereLinuxIPS/node_modules/blessed/lib/helpers.js:137:6)
    at ListTable.Element.strWidth (/opt/StratosphereLinuxIPS/node_modules/blessed/lib/widgets/element.js:2543:15)
    at /opt/StratosphereLinuxIPS/node_modules/blessed/lib/widgets/table.js:71:23
    at Array.forEach (<anonymous>)
    at /opt/StratosphereLinuxIPS/node_modules/blessed/lib/widgets/table.js:70:9
    at Array.forEach (<anonymous>)
    at ListTable.Table._calculateMaxes (/opt/StratosphereLinuxIPS/node_modules/blessed/lib/widgets/table.js:69:13)
    at ListTable.setRows.ListTable.setData (/opt/StratosphereLinuxIPS/node_modules/blessed/lib/widgets/listtable.js:97:8)
    at ListTable.setDataIPInfo (/opt/StratosphereLinuxIPS/modules/kalipso/kalipso_widgets/kalipso_listtable.js:84:17)
    at /opt/StratosphereLinuxIPS/modules/kalipso/kalipso_widgets/kalipso_listtable.js:120:14

**Comment by eldraco** [comment]
Hi! Yes we are working with this error now. 
Thanks for the report! It is an issue with the new ASN code

**Comment by eldraco** [comment]
Here you have a quick patch, try this:

`git apply kalipso-fix-asn-temp.txt`

Here the file
[kalipso-fix-asn-temp.txt](https://github.com/stratosphereips/StratosphereLinuxIPS/files/6784704/kalipso-fix-asn-temp.txt)

We will solve it completely later

**Comment by Locituscom** [comment]
Thanks, but no luck!
I checked out develop as a clean tree and applied the patch. I also updated the PATH so that the kalipso script remains unaltered. Unfortunately it still crashes. But if you're still working on it and are aware of the issue I'm happy to wait for a real fix.

mr@ids:/opt/StratosphereLinuxIPS$ git checkout .
Updated 1 path from the index
mr@ids:/opt/StratosphereLinuxIPS$ git branch
* develop
  master
mr@ids:/opt/StratosphereLinuxIPS$ git apply kalipso-fix-asn-temp.txt
mr@ids:/opt/StratosphereLinuxIPS$ which node
/opt/StratosphereLinuxIPS/node_modules/node/bin/node
mr@ids:/opt/StratosphereLinuxIPS$ ./kalipso.sh
TypeError: text.replace is not a function
    at Object.helpers.stripTags (/opt/StratosphereLinuxIPS/node_modules/blessed/lib/helpers.js:137:6)
    at ListTable.Element.strWidth (/opt/StratosphereLinuxIPS/node_modules/blessed/lib/widgets/element.js:2543:15)
    at /opt/StratosphereLinuxIPS/node_modules/blessed/lib/widgets/table.js:71:23
    at Array.forEach (<anonymous>)
    at /opt/StratosphereLinuxIPS/node_modules/blessed/lib/widgets/table.js:70:9
    at Array.forEach (<anonymous>)
    at ListTable.Table._calculateMaxes (/opt/StratosphereLinuxIPS/node_modules/blessed/lib/widgets/table.js:69:13)
    at ListTable.setRows.ListTable.setData (/opt/StratosphereLinuxIPS/node_modules/blessed/lib/widgets/listtable.js:97:8)
    at ListTable.setDataIPInfo (/opt/StratosphereLinuxIPS/modules/kalipso/kalipso_widgets/kalipso_listtable.js:84:17)
    at /opt/StratosphereLinuxIPS/modules/kalipso/kalipso_widgets/kalipso_listtable.js:120:14

**Comment by kamilababayeva** [comment]
Hello there! I believe I have solved the issue in my last commit. It is pushed to the develop branch. Can you pull and try it again? Here is the commit fa475cd3c1e4e9e36dfb9287f45d7afe2d5e5f6e.

Also after you pull, run slips with the parameter **--clearcache**. The way the ASN is stored in the database has changed, so it is better to clean the database before using Slips.

Let us know if it worked! Thank you!

**Comment by eldraco** [comment]
Try this patch please on top of the other

`git apply kalipso-fix-2-asn-temp.txt`

[kalipso-fix-2-asn-temp.txt](https://github.com/stratosphereips/StratosphereLinuxIPS/files/6785001/kalipso-fix-2-asn-temp.txt)

I'm trying to avoid using the ASN data until we fix it

**Comment by Locituscom** [comment]
Hi, I've pulled the latest develop commit and restarted slips with --clearcache. Let me collect some more data and see if your fix helped.

**Comment by Locituscom** [comment]
It looks like the last commit worked, nothing crashes kalipso so far, and it successfully resolved 1.1.1.3 as ASN CLOUDFLARENET.

Thanks for all the quick help!

**Comment by Locituscom** [comment]
Found a new crash that didn't happen earlier (I think in master branch), when trying to look at i:OutTouples

mr@ids:/opt/StratosphereLinuxIPS$ ./kalipso.sh
TypeError: ip_info_dict.asn.slice is not a function
    at /opt/StratosphereLinuxIPS/modules/kalipso/kalipso_widgets/kalipso_listtable.js:249:61
    at /opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:2154:44
    at eachOfArrayLike (/opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:500:13)
    at eachOf (/opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:551:16)
    at awaitable (/opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:208:32)
    at Object.eachLimit (/opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:2216:16)
    at Object.awaitable (/opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:208:32)
    at /opt/StratosphereLinuxIPS/modules/kalipso/kalipso_widgets/kalipso_listtable.js:232:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/opt/StratosphereLinuxIPS/modules/kalipso/kalipso_widgets/kalipso_listtable.js:249
                              temp_sni, ip_info_dict['asn'].slice(0,20), ip_info_dict['geo'],
                                                            ^

TypeError: ip_info_dict.asn.slice is not a function
    at /opt/StratosphereLinuxIPS/modules/kalipso/kalipso_widgets/kalipso_listtable.js:249:61
    at /opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:2154:44
    at eachOfArrayLike (/opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:500:13)
    at eachOf (/opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:551:16)
    at awaitable (/opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:208:32)
    at Object.eachLimit (/opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:2216:16)
    at Object.awaitable (/opt/StratosphereLinuxIPS/node_modules/async/dist/async.js:208:32)
    at /opt/StratosphereLinuxIPS/modules/kalipso/kalipso_widgets/kalipso_listtable.js:232:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by kamilababayeva** [comment]
Ahhhhhh, wait for me. it is my bad. I fixed it in one place and did not fix it in another...

**Comment by Locituscom** [comment]
No problem! 👍 
I'll just pull the new code when you're ready. :)

**Comment by kamilababayeva** [comment]
Can you pull now? thanks!

**Comment by Locituscom** [comment]
That works great!!

Thanks both of you! 👍
