### ISSUE TITLE
Ajax error viewing alerts

### ISSUE THREAD

**Issue by Nubicola** [stratosphereips/StratosphereLinuxIPS#165]
**Describe the bug**
When I click on "Alerts" for a specific host, I get a popup message: DataTables warning: table id=table_alerts - Ajax error. For more information about this error, please see http://datatables.net/tn/7

from the web_interface.sh I see the following error:
```
192.168.50.31 - - [14/Dec/2022 09:25:46] "GET /analysis/evidence/192.168.50.31/timewindow1/?_=1671008870580 HTTP/1.1" 200 -
[2022-12-14 09:25:47,162] ERROR in app: Exception on /analysis/alerts/192.168.50.31/timewindow1 [GET]
Traceback (most recent call last):
  File "/home/ben/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ben/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ben/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ben/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ben/code/StratosphereLinuxIPS/webinterface/analysis/analysis.py", line 304, in set_alerts
    alert_description = json.loads(evidences[alert_ID])
KeyError: 'b2cd2c75-3af6-4306-b3b8-535a36a264d9'
192.168.50.31 - - [14/Dec/2022 09:25:47] "GET /analysis/alerts/192.168.50.31/timewindow1?_=1671008870581 HTTP/1.1" 500 -
```

Please advise what additional data I can provide to help debug this

**Branch**
master

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox

**Comment by eldraco** [comment]
Hi Nubicola. Thanks for the report. We are working to solve this.
We used to have this error before, and it was fixed, but it seems it is back.
The issue is that sometimes we modify the backend DB structure and some parts of the web are not updated.
Thanks!
