### ISSUE TITLE
ValueError: could not convert string to float: '' in flowmldetection.py

### ISSUE THREAD

**Issue by naturalnetworks** [stratosphereips/StratosphereLinuxIPS#329]
**Describe the bug**
During capture from an interface, the following error pops up quite often.

```
Traceback (most recent call last):
  File "/home/user/StratosphereLinuxIPS/modules/flowmldetection/flowmldetection.py", line 171, in process_features
    dataset.proto = dataset.proto.astype('float64')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/slips/lib/python3.11/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/slips/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "/home/user/slips/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/slips/lib/python3.11/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/slips/lib/python3.11/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/slips/lib/python3.11/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/slips/lib/python3.11/site-packages/pandas/core/dtypes/astype.py", line 138, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''
```

Note that I am receiving a TZSP stream from a router and replaying it to a dummy interface.

**To Reproduce**
1. Set network interface to promisc (or use a dummy interface with tcpreplay)
2. ./slips.py -c config/slips.conf -i <network interface>
3. Confirm data eg tcpdump -i <network interface> -c 10
4. Wait for error to appear

**Expected behavior**
No value errors should appear during normal operation/during an interface capture.

**Branch**
Have tested both Master and Develop, issue seen on both.

**Environment (please complete the following information):**
 - OS: Ubuntu (Raspberri Pi/ARM64)
 - Version: 23.04 (Linux 6.2.0-1004-raspi)
 - Python version: Python 3.11.2
 - Are you running slips in docker or locally? Locally

**Additional context**

Wrapping  "dataset.proto = dataset.proto.astype('float64')" with a try/catch in flowmldetection.py makes the issue go away, but I'm not sure if it's the correct fix.

```
          try:
              # Convert proto to float64
              dataset.proto = dataset.proto.astype('float64')
          except ValueError:
              pass
```

**Comment by robertchonge** [comment]
Hi,Can l work on this issue?

**Comment by eldraco** [comment]
Hi @robertchonge . Yes you are welcome to work on this. However, please see that it was not us reporting the bug, so we don't have the data to reproduce. Maybe @naturalnetworks can give us some

**Comment by eldraco** [comment]
Solved
