### ISSUE TITLE
sqlite error: database disk image is malformed

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#755]
Slips version: 1.0.6
File: CTU-SME-11/CTU-SME-11/Experiment-VM-Microsoft-Windows7AD-1/2023-02-20/raw/2023-02-20-00-00-03-192.168.1.108.pcap
Branch: develop
Commit: f36318c0d3f27f3b25f3b7d30f81b2d686ff730a

```

[Input] We read everything. No more input. Stopping input process. Sent 80017 lineshr: 3. (2023/09/01 13:23:38)


Traceback (most recent call last):ence added: 235. IPs sending

traffic in the last 1 hr: 2. (2023/09/01 13:34:04)

File "/opt/Malware-Project/tools/StratosphereLinuxIPS/modules/timeline/timeline.py", line 258, in process_flow

alt_flow: dict = self.db.get_altflow_from_uid(

File "/opt/Malware-Project/tools/StratosphereLinuxIPS/slips_files/core/database/database_manager.py", line 567, in get_altflow_from_uid

return self.sqlite.get_altflow_from_uid(*args, **kwargs)

File "/opt/Malware-Project/tools/StratosphereLinuxIPS/slips_files/core/database/sqlite_db/database.py", line 86, in get_altflow_from_uid

altflow = self.select('altflows', condition=condition)

File "/opt/Malware-Project/tools/StratosphereLinuxIPS/slips_files/core/database/sqlite_db/database.py", line 314, in select

result = self.fetchall()

File "/opt/Malware-Project/tools/StratosphereLinuxIPS/slips_files/core/database/sqlite_db/database.py", line 339, in fetchall

res = self.cursor.fetchall()

sqlite3.InterfaceError: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.

from error.log

2023/09/01 13:34:09.481603 [Flow Alerts] Traceback (most recent call last):
File "/opt/Malware-Project/tools/StratosphereLinuxIPS/slips_files/common/abstracts.py", line 115, in run
error: bool = self.main()
File "/opt/Malware-Project/tools/StratosphereLinuxIPS/modules/flowalerts/flowalerts.py", line 2066, in main
self.check_dns_without_connection(
File "/opt/Malware-Project/tools/StratosphereLinuxIPS/modules/flowalerts/flowalerts.py", line 759, in check_dns_without_connection
contacted_ips = self.db.get_all_contacted_ips_in_profileid_twid(
File "/opt/Malware-Project/tools/StratosphereLinuxIPS/slips_files/core/database/database_manager.py", line 582, in get_all_contacted_ips_in_profileid_twid
return self.sqlite.get_all_contacted_ips_in_profileid_twid(*args, **kwargs)
File "/opt/Malware-Project/tools/StratosphereLinuxIPS/slips_files/core/database/sqlite_db/database.py", line 97, in get_all_contacted_ips_in_profileid_twid
all_flows: dict = self.get_all_flows_in_profileid_twid(profileid, twid)
File "/opt/Malware-Project/tools/StratosphereLinuxIPS/slips_files/core/database/sqlite_db/database.py", line 113, in get_all_flows_in_profileid_twid
all_flows: list = self.select('flows', condition=condition)
File "/opt/Malware-Project/tools/StratosphereLinuxIPS/slips_files/core/database/sqlite_db/database.py", line 314, in select
result = self.fetchall()
File "/opt/Malware-Project/tools/StratosphereLinuxIPS/slips_files/core/database/sqlite_db/database.py", line 339, in fetchall
res = self.cursor.fetchall()
sqlite3.DatabaseError: database disk image is malformed
```
Created by Alya Gomaa via monday.com integration. 🎉

**Comment by AlyaGomaa** [comment]
no longer happening
