### ISSUE TITLE
The fix_rnn branch is updated and the code is working. Needs to be tested.

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#808]
I merged develop in this branch, but since develop itself is not passing the tests. Then this branch is not passing the tests

**Comment by AlyaGomaa** [comment]
hey @eldraco, when running Slips 
- on this branch `alya/migration_to_python3.10.12` which has the rnn fix
-  cmd: ./slips.py -e 1 -f dataset/test10-mixed-zeek-dir -o alia      
it still has some issues from the RNN module
```
[RNN C&C Detection] Problem in pre_main() line 146                                                                                                                                                                                          
[RNN C&C Detection] Traceback (most recent call last):                                                                                                                                                                                      
  File "/home/alya/Desktop/StratosphereLinuxIPS/slips_files/common/abstracts/module.py", line 146, in run
    error: bool = self.pre_main()
  File "/home/alya/Desktop/StratosphereLinuxIPS/modules/rnn_cc_detection/rnn_cc_detection.py", line 251, in pre_main
    self.tcpmodel = load_model("modules/rnn_cc_detection/rnn_model.h5")
  File "/home/alya/venvs/slips/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/home/alya/venvs/slips/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 199, in load_model_from_hdf5
    model.compile(**saving_utils.compile_args_from_training_config(
  File "/home/alya/venvs/slips/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 212, in compile_args_from_training_config
    optimizer = optimizers.deserialize(optimizer_config)
  File "/home/alya/venvs/slips/lib/python3.8/site-packages/tensorflow/python/keras/optimizers.py", line 83, in deserialize
    return deserialize_keras_object(
  File "/home/alya/venvs/slips/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 346, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "/home/alya/venvs/slips/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 296, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown optimizer: Custom>Adam
```

**Comment by eldraco** [comment]
Weird, that is an old error that I solved already. Why is it in this branch? let me check

**Comment by AlyaGomaa** [comment]
done in #835
