### ISSUE TITLE
export_labeled_flows cause sqlite3 Interface error

### ISSUE THREAD

**Issue by maldwg** [stratosphereips/StratosphereLinuxIPS#976]
**Describe the bug**
When following the official guide to set up Slips in docker, and analyzing a test file provided in the GitHub repository, an error is thrown regarding sqlite3. The error occurs as far as I can tell in the Evidence module, when setting the option to export labeled flows to True. I don't know if this is related, but after any analyzation, the sqlite3 database holds only entries in altflows and flows tables and none in the alerts table. I did not modify any other setting in the slips configuration file. 

The complete logs are:

```
root@DESKTOP-JH34L91:/StratosphereLinuxIPS# ./slips.py -f dataset/test7-malicious.pcap -o ./output_dir 
Slips. Version 1.1

https://stratosphereips.org
---------------------------
[Main] Using redis server on port: 6379
Started Main process [PID 567]
Started PBar process [PID 577]
Starting modules
                Starting the module ARP (Detect ARP attacks) [PID 595]
                Starting the module Flow Alerts (Alerts about flows: long connection, successful ssh, password guessing, self-signed certificate, data exfiltration, etc.) [PID 597]
                Starting the module Flow ML Detection (Train or test a Machine Learning model to detect malicious flows) [PID 599]
                Starting the module HTTP Analyzer (Analyze HTTP flows) [PID 600]
                Starting the module IP Info (Get different info about an IP/MAC address) [PID 601]
                Starting the module Network Discovery (Detect Horizonal, Vertical Port scans, ICMP, and DHCP scans) [PID 602]
                Starting the module Risk IQ (Module to get passive DNS info about IPs from RiskIQ) [PID 603]
                Starting the module RNN C&C Detection (Detect C&C channels based on behavioral letters) [PID 604]
                Starting the module Threat Intelligence (Check if the source IP or destination IP are in a malicious list of IPs) [PID 622]
                Starting the module Timeline (Creates kalipso timeline of what happened in the network based on flows and available data) [PID 624]
                Starting the module Virustotal (IP, domain and file hash lookup on Virustotal) [PID 625]
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
---------------------------
[Main] Disabled Modules: ['template', 'ensembling', 'updatemanager', 'exporting_alerts', 'p2ptrust', 'cesnet', 'blocking', 'leak_detector', 'cyst']
[Evidence] Storing Slips logs in ./output_dir
Started Evidence Process [PID 626]
Started Profiler Process [PID 627]
[Main] Metadata added to ./output_dir/metadata
Started Input Process [PID 628]
[Input] Storing zeek log files in ./output_dir/zeek_files
[Main] Warning: Slips may generate a large amount of traffic by querying TI sites.
[Input] Zeek error. return code: 0 error:b'warning in /opt/zeek/share/zeek/policy/tuning/defaults/__load__.zeek, line 1: deprecated script loaded from /StratosphereLinuxIPS/zeek-scripts/__load__.zeek:25 "Remove in v7.1 The policy/tuning/defaults package is deprecated. The options set here are now the defaults for Zeek in general.";'
Total analyzed IPs so far: 9. Evidence Added: 1. IPs sending traffic in the last 1 hr: 0. Total analyzed IPs so far: 12. Evidence Added: 8. IPs sending traffic in the last 1 hr: 9.Total analyzed IPs so far: 16. Evidence Added: 17. IPs sending traffic in the last 1 hr: 1Total analyzed IPs so far: 16. Evidence Added: 19. IPs sending traffic in the last 1 hr: 1Total analyzed IPs so far: 16. Evidence Added: 21. IPs sending traffic in the last 1 hr: 2Total analyzed IPs so far: 44. Evidence Added: 84. IPs sending traffic in the last 1 hr: 3[Input] We read everything. No more input. Stopping input process. Sent 541 lines
[Input] Stopping. Total lines read: 541
Total analyzed IPs so far: 70. Evidence Added: 143. IPs sending traffic in the last 1 hr: [Main] 4/08/30 10:52:19)
---------------------------
[Main] Stopping Slips
[Main] Analysis of dataset/test7-malicious.pcap finished in 0.69 minutes
[Main]  RNN C&C Detection       Stopped. 12 left.
[Main]  Flow ML Detection       Stopped. 11 left.
[Main]  ARP                     Stopped. 10 left.
[Main]  Input                   Stopped. 9 left.
[Main]  Profiler                Stopped. 8 left.
[Main]  Threat Intelligence     Stopped. 7 left.
[Main]  Timeline                Stopped. 6 left.
[Main]  Progress Bar            Stopped. 5 left.
[Main]  HTTP Analyzer           Stopped. 4 left.
[Main] The following modules are busy working on your data.

['Flow Alerts', 'Network Discovery', 'IP Info', 'Evidence']

You can wait for them to finish, or you can press CTRL-C again to force-kill.

[Main]  Network Discovery       Stopped. 3 left.
[Main]  IP Info                 Stopped. 2 left.
[Main]  Flow Alerts             Stopped. 1 left.
[Main]  Evidence                Stopped. 0 left.
root@DESKTOP-JH34L91:/StratosphereLinuxIPS# ./slips.py -f dataset/test7-malicious.pcap -o ./output_dir 
Slips. Version 1.1

https://stratosphereips.org
---------------------------
[Main] Using redis server on port: 6379
Started Main process [PID 809]
Started PBar process [PID 819]
Starting modules
                Starting the module ARP (Detect ARP attacks) [PID 837]
                Starting the module Flow Alerts (Alerts about flows: long connection, successful ssh, password guessing, self-signed certificate, data exfiltration, etc.) [PID 839]
                Starting the module Flow ML Detection (Train or test a Machine Learning model to detect malicious flows) [PID 841]
                Starting the module HTTP Analyzer (Analyze HTTP flows) [PID 842]
                Starting the module IP Info (Get different info about an IP/MAC address) [PID 843]
                Starting the module Network Discovery (Detect Horizonal, Vertical Port scans, ICMP, and DHCP scans) [PID 844]
                Starting the module Risk IQ (Module to get passive DNS info about IPs from RiskIQ) [PID 845]
                Starting the module RNN C&C Detection (Detect C&C channels based on behavioral letters) [PID 846]
                Starting the module Threat Intelligence (Check if the source IP or destination IP are in a malicious list of IPs) [PID 864]
                Starting the module Timeline (Creates kalipso timeline of what happened in the network based on flows and available data) [PID 866]
                Starting the module Virustotal (IP, domain and file hash lookup on Virustotal) [PID 867]
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
---------------------------
[Main] Disabled Modules: ['template', 'ensembling', 'updatemanager', 'exporting_alerts', 'p2ptrust', 'cesnet', 'blocking', 'leak_detector', 'cyst']
[Evidence] Storing Slips logs in ./output_dir
Started Evidence Process [PID 868]
Started Profiler Process [PID 869]
[Main] Metadata added to ./output_dir/metadata
Started Input Process [PID 870]
[Main] Warning: Slips may generate a large amount of traffic by querying TI sites.
[Input] Storing zeek log files in ./output_dir/zeek_files
[Input] Zeek error. return code: 0 error:b'warning in /opt/zeek/share/zeek/policy/tuning/defaults/__load__.zeek, line 1: deprecated script loaded from /StratosphereLinuxIPS/zeek-scripts/__load__.zeek:25 "Remove in v7.1 The policy/tuning/defaults package is deprecated. The options set here are now the defaults for Zeek in general.";'
Total analyzed IPs so far: 9. Evidence Added: 0. IPs sending traffic in the last 1 hr: 0. Total analyzed IPs so far: 12. Evidence Added: 6. IPs sending traffic in the last 1 hr: 9.Total analyzed IPs so far: 16. Evidence Added: 13. IPs sending traffic in the last 1 hr: 1Total analyzed IPs so far: 16. Evidence Added: 14. IPs sending traffic in the last 1 hr: 9Total analyzed IPs so far: 16. Evidence Added: 18. IPs sending traffic in the last 1 hr: 2Total analyzed IPs so far: 64. Evidence Added: 124. IPs sending traffic in the last 1 hr: [Input] We read everything. No more input. Stopping input process. Sent 541 lines
[Input] Stopping. Total lines read: 541
Total analyzed IPs so far: 95. Evidence Added: 191. IPs sending traffic in the last 1 hr: [Main] 4/08/30 10:59:01)
---------------------------
[Main] Stopping Slips
[Main] Analysis of dataset/test7-malicious.pcap finished in 0.68 minutes
[Main]  Profiler                Stopped. 12 left.
[Main]  HTTP Analyzer           Stopped. 11 left.
[Main]  Timeline                Stopped. 10 left.
[Main]  Input                   Stopped. 9 left.
[Main]  Progress Bar            Stopped. 8 left.
[Main]  Flow ML Detection       Stopped. 7 left.
[Main]  RNN C&C Detection       Stopped. 6 left.
[Main]  ARP                     Stopped. 5 left.
[Main]  Threat Intelligence     Stopped. 4 left.
[Main] The following modules are busy working on your data.

['IP Info', 'Network Discovery', 'Flow Alerts', 'Evidence']

You can wait for them to finish, or you can press CTRL-C again to force-kill.

[Main]  IP Info                 Stopped. 3 left.
[Main]  Network Discovery       Stopped. 2 left.
[Main]  Flow Alerts             Stopped. 1 left.
[Main]  Evidence                Stopped. 0 left.
Traceback (most recent call last):
  File "/StratosphereLinuxIPS/./slips.py", line 62, in <module>
    slips.start()
  File "/StratosphereLinuxIPS/slips/main.py", line 775, in start
    self.proc_man.shutdown_gracefully()
  File "/StratosphereLinuxIPS/managers/process_manager.py", line 767, in shutdown_gracefully
    self.main.db.export_labeled_flows(format_)
  File "/StratosphereLinuxIPS/slips_files/core/database/database_manager.py", line 881, in export_labeled_flows
    self.sqlite.export_labeled_flows(
  File "/StratosphereLinuxIPS/slips_files/core/database/sqlite_db/database.py", line 207, in export_labeled_flows
    for row in self.iterate_flows():
  File "/StratosphereLinuxIPS/slips_files/core/database/sqlite_db/database.py", line 235, in row_generator
    row = self.fetchone()
  File "/StratosphereLinuxIPS/slips_files/core/database/sqlite_db/database.py", line 391, in fetchone
    res = self.cursor.fetchone()
sqlite3.InterfaceError: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
```

**To Reproduce**
1. Use the latest dockerized version of slips
2. setup the container like mentioned in the Readme using 
`docker run --rm -it--net=host --cap-add=NET_ADMIN --name slips stratosphereips/slips:latest`
3. Activate the export labeled flows option in the slips.yaml and set the output to either json or tsv
4. Run a test analyzation for any given file e.g. : `./slips.py -f dataset/test7-malicious.pcap -o ./output_dir `

**Expected behavior**
A successfully analyzation of the file with alerts being logged in alerts.json and alerts.log, as well as labeled_flows in the files labeled_flows.json or .tsv. In the sqlite file itself, the alerts should be inserted into the alerts table. 

**Environment (please complete the following information):**
 - OS: WSL2, Ubuntu
 - Version 22
 - Python version 3.10
 - Are you running slips in docker or locally? yes
 - Docker version (if running slips in docker) Docker version 26.1.2, build 211e74b
 - Slips docker image used (if running slips in docker) stratosphereips/slips:latest, digest: sha256:6a25dd120c0f54e19f78e90101177d58e0e4e442d7265177615b12580dc86666

**Comment by maldwg** [comment]
I guess this is a duplication of https://github.com/stratosphereips/StratosphereLinuxIPS/issues/756 and can be closed
